apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: platform-simulator
  namespace: platform
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: platform-simulator