apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - reaction-webhooks.yaml
  - ../../../policy/gatekeeper/constraint-template.yaml
  - ../../../policy/gatekeeper/constraint-template-disallow-privileged.yaml
  - ../../../policy/gatekeeper/constraint-template-trusted-registries.yaml
  - ../../../policy/gatekeeper/constraints.yaml
  - ../../../observability/prometheus/rules/platform-prometheusrule.yaml
  - ../../../observability/alertmanager/alertmanager-config.yaml
  - ../../../security/falco/rules/platform-rules-configmap.yaml